/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.PedidoCtrl;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author HP
 */
public class AplazarPedidoForm extends javax.swing.JPanel {

    /**
     * Creates new form ActualizarPedidoForm
     */
    
    PedidoCtrl pedido= new PedidoCtrl();
    public AplazarPedidoForm() {
        initComponents();
        this.cbNumero.setModel(getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        panelAplazar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnAplazar = new javax.swing.JButton();
        cbNumero = new javax.swing.JComboBox<>();

        jLabel3.setText("jLabel3");

        jLabel1.setText("Pedido Aplazado");

        jLabel2.setText("Número Pedido");

        jLabel4.setText("Motivo");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnAplazar.setText("Aceptar");
        btnAplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAplazarLayout = new javax.swing.GroupLayout(panelAplazar);
        panelAplazar.setLayout(panelAplazarLayout);
        panelAplazarLayout.setHorizontalGroup(
            panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAplazarLayout.createSequentialGroup()
                .addGroup(panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAplazarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(panelAplazarLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(btnVolver))
                        .addGap(18, 18, 18)
                        .addGroup(panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMotivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(btnAplazar)
                            .addComponent(cbNumero, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelAplazarLayout.setVerticalGroup(
            panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAplazarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnAplazar))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAplazar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAplazar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        PedidosView pedidos= new PedidosView();
        pedidos.setSize(panelAplazar.getSize());
        panelAplazar.removeAll();
        panelAplazar.add(pedidos);
        panelAplazar.revalidate();
        panelAplazar.repaint();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplazarActionPerformed
       Date date= this.getRandomDate();
    
        java.sql.Date sql= new java.sql.Date(date.getTime());
        pedido.updatePedido(Long.parseLong(cbNumero.getSelectedItem().toString()), "Aplazado", sql,txtMotivo.getText());
        txtMotivo.setText("");
    }//GEN-LAST:event_btnAplazarActionPerformed

    public DefaultComboBoxModel getModel(){
        DefaultComboBoxModel modelo= new DefaultComboBoxModel();
        for (int i = 0; i < pedido.selectPedido().size(); i++) {
            modelo.addElement(pedido.selectPedido().get(i).getId());
        }
        return modelo;
    }
    
    public  Date getRandomDate() {
        Date date= pedido.selectPedido(Long.parseLong(cbNumero.getSelectedItem().toString())).getFechaEntrega();
		Random rand = new Random();
		SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd ");
		Calendar cal = Calendar.getInstance();
		cal.set(date.getYear(), date.getMonth(), date.getDay());
		long start = cal.getTimeInMillis();
		cal.set(2022, 8, 30);
		long end = cal.getTimeInMillis();
		Date d = new Date(start + (long) (rand.nextDouble() * (end - start)));
		//System.out.println(format.format(d));
		return d;
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplazar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelAplazar;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables
}
