/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.PedidoCtrl;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AplazarPedidoForm extends javax.swing.JPanel {

    /**
     * Creates new form ActualizarPedidoForm
     */
    
    PedidoCtrl pedido= new PedidoCtrl();
    public AplazarPedidoForm() {
        initComponents();
        this.cbNumero.setModel(getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        panelAplazar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnAplazar = new javax.swing.JButton();
        cbNumero = new javax.swing.JComboBox<>();

        jLabel3.setText("jLabel3");

        panelAplazar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Pedido Aplazado");

        jLabel2.setText("Número Pedido");

        jLabel4.setText("Motivo");

        txtMotivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMotivoKeyTyped(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(255, 153, 51));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-back-32.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnAplazar.setBackground(new java.awt.Color(255, 153, 51));
        btnAplazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-rescheduling-a-task-32.png"))); // NOI18N
        btnAplazar.setText("Aplazar");
        btnAplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAplazarLayout = new javax.swing.GroupLayout(panelAplazar);
        panelAplazar.setLayout(panelAplazarLayout);
        panelAplazarLayout.setHorizontalGroup(
            panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAplazarLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAplazarLayout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAplazar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAplazarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAplazarLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAplazarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        panelAplazarLayout.setVerticalGroup(
            panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAplazarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(panelAplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAplazar)
                    .addComponent(btnVolver))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAplazar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAplazar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        PedidosView pedidos= new PedidosView();
        pedidos.setSize(panelAplazar.getWidth(),panelAplazar.getHeight());
        this.setLayout(null);
        this.panelAplazar.removeAll();
        this.panelAplazar.add(pedidos);
        this.panelAplazar.revalidate();
        this.panelAplazar.repaint();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplazarActionPerformed
       Date date= this.getRandomDate();
    
        java.sql.Date sql= new java.sql.Date(date.getTime());
        pedido.updatePedido(Long.parseLong(cbNumero.getSelectedItem().toString()), "Aplazado", sql,txtMotivo.getText());
        JOptionPane.showMessageDialog(null, "La nueva fecha de entrega es "+sql);
        txtMotivo.setText("");
    }//GEN-LAST:event_btnAplazarActionPerformed

    private void txtMotivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotivoKeyTyped
         char car=evt.getKeyChar();
      
       if((car<'a' || car>'z') && (car<'A'||car>'Z') && (car!=(char)KeyEvent.VK_BACK_SPACE)&&(car!=(char)KeyEvent.VK_SPACE)){
           evt.consume();
           getToolkit().beep();
           JOptionPane.showMessageDialog(this, "Solo se admite texto","Advertencia", JOptionPane.WARNING_MESSAGE);
       }
          if(txtMotivo.getText().length() >= 21)
    {
        evt.consume();
        JOptionPane.showMessageDialog(this,"Solo 20 caracteres","Error de formato",JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_txtMotivoKeyTyped

    public DefaultComboBoxModel getModel(){
        DefaultComboBoxModel modelo= new DefaultComboBoxModel();
        for (int i = 0; i < pedido.selectPedido().size(); i++) {
            modelo.addElement(pedido.selectPedido().get(i).getId());
        }
        return modelo;
    }
    
    public  Date getRandomDate() {
        Date date= pedido.selectPedido(Long.parseLong(cbNumero.getSelectedItem().toString())).getFechaEntrega();
		     
                      
        Random rand = new Random();
		SimpleDateFormat format = new SimpleDateFormat("yyyy");
                String año =format.format(date);
                int años=Integer.parseInt(año);
                System.out.println(años);
		Calendar cal = Calendar.getInstance();
		cal.set(años, date.getMonth(), date.getDay());
		long start = cal.getTimeInMillis();
		cal.set(2022, 8, 30);
		long end = cal.getTimeInMillis();
		Date d = new Date(start + (long) (rand.nextDouble() * (end - start)));
		//System.out.println(format.format(d));
		return d;
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplazar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelAplazar;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables
}
